### ISSUE TITLE
Replace DevCon with PnPUtil for (un)install

### ISSUE THREAD

**Issue by forderud** [forderud/IntelliMouseDriver#17]
Reported Microsoft issue: https://github.com/MicrosoftDocs/windows-driver-docs/issues/3641

Goal: Avoid need for distributing `DevCon` for installation & uninstallation, since it's not intended for distribution.

Problem: INSTALL.bat doesn't work if mouse isn't plugged in.

Things to test:
* Add devgen `/subtree` argument: Doesn't help
* Switch to devgen SWD and add `/parent` argument: TBD
* 

Limitations:
* The `PNPUTIL /enable-device /deviceid <device ID>` switch is only available from Windows 11 version 21H2. Can therefore not be used on the latest Win10 LTSC 21H2.

Doc:
* https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/devcon-install#recommended-replacement recommends `devgen /add /bus ROOT /hardwareid HardwareID`
* [DEVGEN /add ...](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/devgen-command-syntax#add)
* https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/pnputil
* https://learn.microsoft.com/en-us/windows-hardware/drivers/install/inf-models-section
* https://stackoverflow.com/questions/5769786/installing-filter-drivers-to-an-existing-device ([VBoxMouse.inf](https://www.virtualbox.org/browser/vbox/trunk/src/VBox/Additions/WINNT/Mouse/NT5/VBoxMouse.inf) sources)

**Comment by forderud** [comment]
## DevCon install impl
```
    // Use the INF File to extract the Class GUID.
    if (!SetupDiGetINFClass(InfPath,&ClassGUID,ClassName,sizeof(ClassName)/sizeof(ClassName[0]),0))
        goto final;

    // Create the container for the to-be-created Device Information Element.
    DeviceInfoSet = SetupDiCreateDeviceInfoList(&ClassGUID,0);
    if(DeviceInfoSet == INVALID_HANDLE_VALUE)
        goto final;

    // Now create the element.
    // Use the Class GUID and Name from the INF file.
    DeviceInfoData.cbSize = sizeof(SP_DEVINFO_DATA);
    if (!SetupDiCreateDeviceInfo(DeviceInfoSet,
        ClassName,
        &ClassGUID,
        NULL,
        0,
        DICD_GENERATE_ID,
        &DeviceInfoData))
        goto final;

    // Add the HardwareID to the Device's HardwareID property.
    if(!SetupDiSetDeviceRegistryProperty(DeviceInfoSet,
        &DeviceInfoData,
        SPDRP_HARDWAREID,
        (LPBYTE)hwIdList,
        ((DWORD)_tcslen(hwIdList)+1+1)*sizeof(TCHAR)))
        goto final;

    // Transform the registry element into an actual devnode
    // in the PnP HW tree.
    if (!SetupDiCallClassInstaller(DIF_REGISTERDEVICE,
        DeviceInfoSet,
        &DeviceInfoData))
        goto final;
```

**Comment by forderud** [comment]
DevGen/pnputil output:
```
>devgen /add /bus ROOT /hardwareid "HID\VID_045E&PID_082A&MI_01&Col05"
Microsoft Device Generator

Device successfully created. Device Instance ID: ROOT\DEVGEN\{B2DA5952-25C1-2A49-95A5-10E69C27BBB1}

>PNPUTIL /add-driver TailLight.inf /install /reboot
Microsoft PnP Utility

Adding driver package:  TailLight.inf
Driver package added successfully.
Published Name:         oem44.inf
Driver package is up-to-date on device: HID\VID_045E&PID_082A&MI_01&Col05\7&181f730b&0&0004
Driver package installed on device: ROOT\DEVGEN\{B2DA5952-25C1-2A49-95A5-10E69C27BBB1}

Total driver packages:  1
Added driver packages:  1

>pnputil /enum-devices /instanceid "ROOT\DEVGEN\{B2DA5952-25C1-2A49-95A5-10E69C27BBB1}" /drivers
Microsoft PnP Utility

Instance ID:                ROOT\DEVGEN\{B2DA5952-25C1-2A49-95A5-10E69C27BBB1}
Device Description:         IntelliMouse TailLight filter driver
Class Name:                 HIDClass
Class GUID:                 {745a17a0-74d3-11d0-b6fe-00a0c90f57da}
Manufacturer Name:          IntelliMouse sample project
Status:                     Stopped
Driver Name:                oem44.inf
Matching Drivers:
    Driver Name:            oem44.inf
    Original Name:          taillight.inf
    Provider Name:          IntelliMouse sample project
    Class Name              HIDClass
    Class GUID:             {745a17a0-74d3-11d0-b6fe-00a0c90f57da}
    Driver Version:         09/22/2023 11.39.12.32
    Matching Device ID:     HID\VID_045E&PID_082A&MI_01&Col05
    Driver Rank:            80FF0000
    Driver Status:          Best Ranked / Installed
```

**Comment by ManOnTheMountainTech** [comment]
https://learn.microsoft.com/en-us/windows-hardware/drivers/develop/preparing-a-computer-for-manual-driver-deployment. It may be possible to have the certificate pre-insalled in the BIOS also.

**Comment by forderud** [comment]
> https://learn.microsoft.com/en-us/windows-hardware/drivers/develop/preparing-a-computer-for-manual-driver-deployment. It may be possible to have the certificate pre-insalled in the BIOS also. Tested and validated using pnputil and the intellimouse certificate.

Sorry, but I don't think that link is relevant here, since it describes how to use DevCon for driver deployment. The `INSTAL_*.bat` scripts are already doing that. The request here is to _avoid_ using DevCon.

**Comment by ManOnTheMountainTech** [comment]
I typed too soon. I tested using pnputil. Installation using pnputil was working for both install and uninstall.

**Comment by forderud** [comment]
> I typed too soon. I tested using pnputil. Installation using pnputil was working for both install and uninstall.

Sounds very interesting. Can you then please provide detailed instructions for how to install the driver _without_ DevCon, so that I can try to reproduce on my own computer?
