### ISSUE TITLE
Doesn't work if enabling "Use Dynamic Lighting on my devices"

### ISSUE THREAD

**Issue by forderud** [forderud/IntelliMouseDriver#36]
## Problem description from Bryan
1)	When “Xbox dynamic lighting” is on, I am **unable** to change the color of the lights with Microsoft Mouse and Keyboard Center
2)	When “Xbox dynamic lighting” is off, I can change the color of the lights with Microsoft Mouse and Keyboard Center

This is what I have in device manager:
![image](https://github.com/forderud/IntelliMouseDriver/assets/2671400/d027d293-0687-4f1c-8f7e-ae9e5e9f9bc7)

 

## To investigate
Might need to update https://github.com/forderud/IntelliMouseDriver/wiki/Driver-testing#driver-testing-safety-control

**Comment by ManOnTheMountainTech** [comment]
Newer builds of Windows have dynamic lighting in Settings | Personalization.
If "Use Dynamic Lighting on my devices" is on, then Mouse and Keyboard Center cannot change the color when "Enable XBox dynamic lighting effect is on.
If "Use Dynamic Lighting on my devices" is off, then Mouse and Keyboard Center can change the color when "Enable XBox dynamic lighting effect is on.
I am conducting experiments to see how this effects the upper filter driver.

**Comment by ManOnTheMountainTech** [comment]
Observation: When "Use Dynamic Lighting on my devices" is enabled, IntelliMouse.ps1 is not able to change the taillight color
Settings | Disabled |  
Microsoft Mouse… | Disabled | TRUE
Settings | Disabled |  
Microsoft Mouse… | Enabled | TRUE
Settings | Enabled |  
Microsoft Mouse… | Disabled | TRUE
Settings | Enabled |  
Microsoft Mouse… | Enabled | FALSE
![image](https://github.com/forderud/IntelliMouseDriver/assets/25311999/4927f990-b3cb-4c5e-b891-a9bea2d67b49)

**Comment by forderud** [comment]
Closing issue, since it doesn't seem to be caused by the driver in this repo.
